// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Original /assets URL → [intrinsicWidth, intrinsicHeight, webpVariantWidths, hasAvif, mobileCropWidth]

export type ImageManifestRow = readonly [number, number, readonly number[], 0 | 1, number];

export const imageManifest: Record<string, ImageManifestRow> = {
  "/assets/pack-sambar-powder.webp": [933,1400,[160,200,256,280,320,420,480,600,720],0,0],
  "/assets/pack-rasam-powder.webp": [407,611,[160,200,256,280,320,407],0,0],
  "/assets/pack-turmeric-powder.webp": [868,1302,[160,200,256,280,320,420,480,600,720],0,0],
  "/assets/pack-red-chilli-powder.webp": [933,1400,[160,200,256,280,320,420,480,600,720],0,0],
  "/assets/pack-coriander-powder.webp": [933,1400,[160,200,256,280,320,420,480,600,720],0,0],
  "/assets/pack-cumin-powder.webp": [795,1193,[160,200,256,280,320,420,480,600,720],0,0],
  "/assets/pack-pepper-powder.webp": [902,1353,[160,200,256,280,320,420,480,600,720],0,0],
  "/assets/pack-garam-masala.webp": [933,1400,[160,200,256,280,320,420,480,600,720],0,0],
  "/assets/hero-video-poster_e92afce6.webp": [1440,810,[960,1440],1,720],
  "/assets/story-spice-mortar_d4ded661.jpg": [1200,776,[480,720,960],0,0],
  "/assets/best-masala-manufacturer-in-chennai.webp": [1288,719,[400,600,700,800,1280],0,0],
  "/assets/masala-manufacturer-vs-supplier-vs-distributor.webp": [1678,937,[400,600,700,800,1280],0,0],
  "/assets/masala-supplier-supermarkets-chennai-cover.jpg": [1024,571,[400,600,700,800,1024],0,0],
  "/assets/how-to-store-indian-spice-powders.jpg": [1376,768,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-good-spice-cover-web_caaa742d.webp": [1280,853,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-supplier-cost-cover-web_493aea4d.webp": [1280,720,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-lunch-box-cover-web_d0df26a5.webp": [1280,720,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-spice-quality-cover-web_966bae04.webp": [1280,720,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-garam-masala-cover-web_977e210e.webp": [1280,725,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-spice-label-cover-web_458a4d2d.webp": [1280,853,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-sambar-blog-cover-web_727590c6.webp": [1280,853,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-good-spice-cover-web.webp": [1280,853,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-supplier-cost-cover-web.webp": [1280,720,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-lunch-box-cover-web.webp": [1280,720,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-spice-quality-cover-web.webp": [1280,720,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-garam-masala-cover-web.webp": [1280,725,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-spice-label-cover-web.webp": [1280,853,[400,600,700,800,1280],0,0],
  "/assets/hipa-original-sambar-blog-cover-web.webp": [1280,853,[400,600,700,800,1280],0,0],
  "/assets/logo_a24808ac.png": [389,453,[48,96,144],0,0],
};
